; GENERATED by tools/build_sections.py - per-section reduced backgrounds

.section ".rodata_bg_L1_S0" superfree
bg_L1_S0_pic: .incbin "res/bg_L1_S0r.pic"
bg_L1_S0_picend:
bg_L1_S0_map: .incbin "res/bg_L1_S0r.map"
bg_L1_S0_pal: .incbin "res/bg_L1_S0r.pal"
.ends

.section ".rodata_bg_L1_S1" superfree
bg_L1_S1_pic: .incbin "res/bg_L1_S1r.pic"
bg_L1_S1_picend:
bg_L1_S1_map: .incbin "res/bg_L1_S1r.map"
bg_L1_S1_pal: .incbin "res/bg_L1_S1r.pal"
.ends

.section ".rodata_bg_L1_S2" superfree
bg_L1_S2_pic: .incbin "res/bg_L1_S2r.pic"
bg_L1_S2_picend:
bg_L1_S2_map: .incbin "res/bg_L1_S2r.map"
bg_L1_S2_pal: .incbin "res/bg_L1_S2r.pal"
.ends

.section ".rodata_bg_L1_S3" superfree
bg_L1_S3_pic: .incbin "res/bg_L1_S3r.pic"
bg_L1_S3_picend:
bg_L1_S3_map: .incbin "res/bg_L1_S3r.map"
bg_L1_S3_pal: .incbin "res/bg_L1_S3r.pal"
.ends

.section ".rodata_bg_L2_S0" superfree
bg_L2_S0_pic: .incbin "res/bg_L2_S0r.pic"
bg_L2_S0_picend:
bg_L2_S0_map: .incbin "res/bg_L2_S0r.map"
bg_L2_S0_pal: .incbin "res/bg_L2_S0r.pal"
.ends

.section ".rodata_bg_L2_S1" superfree
bg_L2_S1_pic: .incbin "res/bg_L2_S1r.pic"
bg_L2_S1_picend:
bg_L2_S1_map: .incbin "res/bg_L2_S1r.map"
bg_L2_S1_pal: .incbin "res/bg_L2_S1r.pal"
.ends

.section ".rodata_bg_L2_S2" superfree
bg_L2_S2_pic: .incbin "res/bg_L2_S2r.pic"
bg_L2_S2_picend:
bg_L2_S2_map: .incbin "res/bg_L2_S2r.map"
bg_L2_S2_pal: .incbin "res/bg_L2_S2r.pal"
.ends

.section ".rodata_bg_L2_S3" superfree
bg_L2_S3_pic: .incbin "res/bg_L2_S3r.pic"
bg_L2_S3_picend:
bg_L2_S3_map: .incbin "res/bg_L2_S3r.map"
bg_L2_S3_pal: .incbin "res/bg_L2_S3r.pal"
.ends

.section ".rodata_bg_L3_S0" superfree
bg_L3_S0_pic: .incbin "res/bg_L3_S0r.pic"
bg_L3_S0_picend:
bg_L3_S0_map: .incbin "res/bg_L3_S0r.map"
bg_L3_S0_pal: .incbin "res/bg_L3_S0r.pal"
.ends

.section ".rodata_bg_L3_S1" superfree
bg_L3_S1_pic: .incbin "res/bg_L3_S1r.pic"
bg_L3_S1_picend:
bg_L3_S1_map: .incbin "res/bg_L3_S1r.map"
bg_L3_S1_pal: .incbin "res/bg_L3_S1r.pal"
.ends

.section ".rodata_bg_L3_S2" superfree
bg_L3_S2_pic: .incbin "res/bg_L3_S2r.pic"
bg_L3_S2_picend:
bg_L3_S2_map: .incbin "res/bg_L3_S2r.map"
bg_L3_S2_pal: .incbin "res/bg_L3_S2r.pal"
.ends

.section ".rodata_bg_L3_S3" superfree
bg_L3_S3_pic: .incbin "res/bg_L3_S3r.pic"
bg_L3_S3_picend:
bg_L3_S3_map: .incbin "res/bg_L3_S3r.map"
bg_L3_S3_pal: .incbin "res/bg_L3_S3r.pal"
.ends

.section ".rodata_bg_L3_S4" superfree
bg_L3_S4_pic: .incbin "res/bg_L3_S4r.pic"
bg_L3_S4_picend:
bg_L3_S4_map: .incbin "res/bg_L3_S4r.map"
bg_L3_S4_pal: .incbin "res/bg_L3_S4r.pal"
.ends

.section ".rodata_bg_L3_S5" superfree
bg_L3_S5_pic: .incbin "res/bg_L3_S5r.pic"
bg_L3_S5_picend:
bg_L3_S5_map: .incbin "res/bg_L3_S5r.map"
bg_L3_S5_pal: .incbin "res/bg_L3_S5r.pal"
.ends

.section ".rodata_bg_L3_S6" superfree
bg_L3_S6_pic: .incbin "res/bg_L3_S6r.pic"
bg_L3_S6_picend:
bg_L3_S6_map: .incbin "res/bg_L3_S6r.map"
bg_L3_S6_pal: .incbin "res/bg_L3_S6r.pal"
.ends

.section ".rodata_bg_L3_S7" superfree
bg_L3_S7_pic: .incbin "res/bg_L3_S7r.pic"
bg_L3_S7_picend:
bg_L3_S7_map: .incbin "res/bg_L3_S7r.map"
bg_L3_S7_pal: .incbin "res/bg_L3_S7r.pal"
.ends

.section ".rodata_bg_L3_S8" superfree
bg_L3_S8_pic: .incbin "res/bg_L3_S8r.pic"
bg_L3_S8_picend:
bg_L3_S8_map: .incbin "res/bg_L3_S8r.map"
bg_L3_S8_pal: .incbin "res/bg_L3_S8r.pal"
.ends

.section ".rodata_bg_L4_S0" superfree
bg_L4_S0_pic: .incbin "res/bg_L4_S0r.pic"
bg_L4_S0_picend:
bg_L4_S0_map: .incbin "res/bg_L4_S0r.map"
bg_L4_S0_pal: .incbin "res/bg_L4_S0r.pal"
.ends

.section ".rodata_bg_L4_S1" superfree
bg_L4_S1_pic: .incbin "res/bg_L4_S1r.pic"
bg_L4_S1_picend:
bg_L4_S1_map: .incbin "res/bg_L4_S1r.map"
bg_L4_S1_pal: .incbin "res/bg_L4_S1r.pal"
.ends

.section ".rodata_bg_L4_S2" superfree
bg_L4_S2_pic: .incbin "res/bg_L4_S2r.pic"
bg_L4_S2_picend:
bg_L4_S2_map: .incbin "res/bg_L4_S2r.map"
bg_L4_S2_pal: .incbin "res/bg_L4_S2r.pal"
.ends

.section ".rodata_bg_L4_S3" superfree
bg_L4_S3_pic: .incbin "res/bg_L4_S3r.pic"
bg_L4_S3_picend:
bg_L4_S3_map: .incbin "res/bg_L4_S3r.map"
bg_L4_S3_pal: .incbin "res/bg_L4_S3r.pal"
.ends

.section ".rodata_bg_L4_S4" superfree
bg_L4_S4_pic: .incbin "res/bg_L4_S4r.pic"
bg_L4_S4_picend:
bg_L4_S4_map: .incbin "res/bg_L4_S4r.map"
bg_L4_S4_pal: .incbin "res/bg_L4_S4r.pal"
.ends

.section ".rodata_bg_L4_S5" superfree
bg_L4_S5_pic: .incbin "res/bg_L4_S5r.pic"
bg_L4_S5_picend:
bg_L4_S5_map: .incbin "res/bg_L4_S5r.map"
bg_L4_S5_pal: .incbin "res/bg_L4_S5r.pal"
.ends

.section ".rodata_bg_L4_S6" superfree
bg_L4_S6_pic: .incbin "res/bg_L4_S6r.pic"
bg_L4_S6_picend:
bg_L4_S6_map: .incbin "res/bg_L4_S6r.map"
bg_L4_S6_pal: .incbin "res/bg_L4_S6r.pal"
.ends

.section ".rodata_bg_L4_S7" superfree
bg_L4_S7_pic: .incbin "res/bg_L4_S7r.pic"
bg_L4_S7_picend:
bg_L4_S7_map: .incbin "res/bg_L4_S7r.map"
bg_L4_S7_pal: .incbin "res/bg_L4_S7r.pal"
.ends

.section ".rodata_bg_L4_S8" superfree
bg_L4_S8_pic: .incbin "res/bg_L4_S8r.pic"
bg_L4_S8_picend:
bg_L4_S8_map: .incbin "res/bg_L4_S8r.map"
bg_L4_S8_pal: .incbin "res/bg_L4_S8r.pal"
.ends

.section ".rodata_bg_L5_S0" superfree
bg_L5_S0_pic: .incbin "res/bg_L5_S0r.pic"
bg_L5_S0_picend:
bg_L5_S0_map: .incbin "res/bg_L5_S0r.map"
bg_L5_S0_pal: .incbin "res/bg_L5_S0r.pal"
.ends

.section ".rodata_bg_L5_S1" superfree
bg_L5_S1_pic: .incbin "res/bg_L5_S1r.pic"
bg_L5_S1_picend:
bg_L5_S1_map: .incbin "res/bg_L5_S1r.map"
bg_L5_S1_pal: .incbin "res/bg_L5_S1r.pal"
.ends

.section ".rodata_bg_L5_S2" superfree
bg_L5_S2_pic: .incbin "res/bg_L5_S2r.pic"
bg_L5_S2_picend:
bg_L5_S2_map: .incbin "res/bg_L5_S2r.map"
bg_L5_S2_pal: .incbin "res/bg_L5_S2r.pal"
.ends

.section ".rodata_bg_L5_S3" superfree
bg_L5_S3_pic: .incbin "res/bg_L5_S3r.pic"
bg_L5_S3_picend:
bg_L5_S3_map: .incbin "res/bg_L5_S3r.map"
bg_L5_S3_pal: .incbin "res/bg_L5_S3r.pal"
.ends

.section ".rodata_bg_L5_S4" superfree
bg_L5_S4_pic: .incbin "res/bg_L5_S4r.pic"
bg_L5_S4_picend:
bg_L5_S4_map: .incbin "res/bg_L5_S4r.map"
bg_L5_S4_pal: .incbin "res/bg_L5_S4r.pal"
.ends

.section ".rodata_bg_L5_S5" superfree
bg_L5_S5_pic: .incbin "res/bg_L5_S5r.pic"
bg_L5_S5_picend:
bg_L5_S5_map: .incbin "res/bg_L5_S5r.map"
bg_L5_S5_pal: .incbin "res/bg_L5_S5r.pal"
.ends

.section ".rodata_bg_L5_S6" superfree
bg_L5_S6_pic: .incbin "res/bg_L5_S6r.pic"
bg_L5_S6_picend:
bg_L5_S6_map: .incbin "res/bg_L5_S6r.map"
bg_L5_S6_pal: .incbin "res/bg_L5_S6r.pal"
.ends

.section ".rodata_bg_L5_S7" superfree
bg_L5_S7_pic: .incbin "res/bg_L5_S7r.pic"
bg_L5_S7_picend:
bg_L5_S7_map: .incbin "res/bg_L5_S7r.map"
bg_L5_S7_pal: .incbin "res/bg_L5_S7r.pal"
.ends

.section ".rodata_bg_L5_S8" superfree
bg_L5_S8_pic: .incbin "res/bg_L5_S8r.pic"
bg_L5_S8_picend:
bg_L5_S8_map: .incbin "res/bg_L5_S8r.map"
bg_L5_S8_pal: .incbin "res/bg_L5_S8r.pal"
.ends

.section ".rodata_bg_L5_S9" superfree
bg_L5_S9_pic: .incbin "res/bg_L5_S9r.pic"
bg_L5_S9_picend:
bg_L5_S9_map: .incbin "res/bg_L5_S9r.map"
bg_L5_S9_pal: .incbin "res/bg_L5_S9r.pal"
.ends

.section ".rodata_bg_L5_S10" superfree
bg_L5_S10_pic: .incbin "res/bg_L5_S10r.pic"
bg_L5_S10_picend:
bg_L5_S10_map: .incbin "res/bg_L5_S10r.map"
bg_L5_S10_pal: .incbin "res/bg_L5_S10r.pal"
.ends

.section ".rodata_bg_L5_S11" superfree
bg_L5_S11_pic: .incbin "res/bg_L5_S11r.pic"
bg_L5_S11_picend:
bg_L5_S11_map: .incbin "res/bg_L5_S11r.map"
bg_L5_S11_pal: .incbin "res/bg_L5_S11r.pal"
.ends

.section ".rodata_bg_L6_S0" superfree
bg_L6_S0_pic: .incbin "res/bg_L6_S0r.pic"
bg_L6_S0_picend:
bg_L6_S0_map: .incbin "res/bg_L6_S0r.map"
bg_L6_S0_pal: .incbin "res/bg_L6_S0r.pal"
.ends

.section ".rodata_bg_L6_S1" superfree
bg_L6_S1_pic: .incbin "res/bg_L6_S1r.pic"
bg_L6_S1_picend:
bg_L6_S1_map: .incbin "res/bg_L6_S1r.map"
bg_L6_S1_pal: .incbin "res/bg_L6_S1r.pal"
.ends

.section ".rodata_bg_L6_S2" superfree
bg_L6_S2_pic: .incbin "res/bg_L6_S2r.pic"
bg_L6_S2_picend:
bg_L6_S2_map: .incbin "res/bg_L6_S2r.map"
bg_L6_S2_pal: .incbin "res/bg_L6_S2r.pal"
.ends

.section ".rodata_bg_L6_S3" superfree
bg_L6_S3_pic: .incbin "res/bg_L6_S3r.pic"
bg_L6_S3_picend:
bg_L6_S3_map: .incbin "res/bg_L6_S3r.map"
bg_L6_S3_pal: .incbin "res/bg_L6_S3r.pal"
.ends

.section ".rodata_bg_L6_S4" superfree
bg_L6_S4_pic: .incbin "res/bg_L6_S4r.pic"
bg_L6_S4_picend:
bg_L6_S4_map: .incbin "res/bg_L6_S4r.map"
bg_L6_S4_pal: .incbin "res/bg_L6_S4r.pal"
.ends

.section ".rodata_bg_L6_S5" superfree
bg_L6_S5_pic: .incbin "res/bg_L6_S5r.pic"
bg_L6_S5_picend:
bg_L6_S5_map: .incbin "res/bg_L6_S5r.map"
bg_L6_S5_pal: .incbin "res/bg_L6_S5r.pal"
.ends

.section ".rodata_bg_L6_S6" superfree
bg_L6_S6_pic: .incbin "res/bg_L6_S6r.pic"
bg_L6_S6_picend:
bg_L6_S6_map: .incbin "res/bg_L6_S6r.map"
bg_L6_S6_pal: .incbin "res/bg_L6_S6r.pal"
.ends

.section ".rodata_bg_L6_S7" superfree
bg_L6_S7_pic: .incbin "res/bg_L6_S7r.pic"
bg_L6_S7_picend:
bg_L6_S7_map: .incbin "res/bg_L6_S7r.map"
bg_L6_S7_pal: .incbin "res/bg_L6_S7r.pal"
.ends

.section ".rodata_bg_L6_S8" superfree
bg_L6_S8_pic: .incbin "res/bg_L6_S8r.pic"
bg_L6_S8_picend:
bg_L6_S8_map: .incbin "res/bg_L6_S8r.map"
bg_L6_S8_pal: .incbin "res/bg_L6_S8r.pal"
.ends

.section ".rodata_bg_L6_S9" superfree
bg_L6_S9_pic: .incbin "res/bg_L6_S9r.pic"
bg_L6_S9_picend:
bg_L6_S9_map: .incbin "res/bg_L6_S9r.map"
bg_L6_S9_pal: .incbin "res/bg_L6_S9r.pal"
.ends

.section ".rodata_bg_L6_S10" superfree
bg_L6_S10_pic: .incbin "res/bg_L6_S10r.pic"
bg_L6_S10_picend:
bg_L6_S10_map: .incbin "res/bg_L6_S10r.map"
bg_L6_S10_pal: .incbin "res/bg_L6_S10r.pal"
.ends

.section ".rodata_bg_L6_S11" superfree
bg_L6_S11_pic: .incbin "res/bg_L6_S11r.pic"
bg_L6_S11_picend:
bg_L6_S11_map: .incbin "res/bg_L6_S11r.map"
bg_L6_S11_pal: .incbin "res/bg_L6_S11r.pal"
.ends

.section ".rodata_bg_L7_S0" superfree
bg_L7_S0_pic: .incbin "res/bg_L7_S0r.pic"
bg_L7_S0_picend:
bg_L7_S0_map: .incbin "res/bg_L7_S0r.map"
bg_L7_S0_pal: .incbin "res/bg_L7_S0r.pal"
.ends

.section ".rodata_bg_L7_S1" superfree
bg_L7_S1_pic: .incbin "res/bg_L7_S1r.pic"
bg_L7_S1_picend:
bg_L7_S1_map: .incbin "res/bg_L7_S1r.map"
bg_L7_S1_pal: .incbin "res/bg_L7_S1r.pal"
.ends

.section ".rodata_bg_L7_S2" superfree
bg_L7_S2_pic: .incbin "res/bg_L7_S2r.pic"
bg_L7_S2_picend:
bg_L7_S2_map: .incbin "res/bg_L7_S2r.map"
bg_L7_S2_pal: .incbin "res/bg_L7_S2r.pal"
.ends

.section ".rodata_bg_L7_S3" superfree
bg_L7_S3_pic: .incbin "res/bg_L7_S3r.pic"
bg_L7_S3_picend:
bg_L7_S3_map: .incbin "res/bg_L7_S3r.map"
bg_L7_S3_pal: .incbin "res/bg_L7_S3r.pal"
.ends

.section ".rodata_bg_L7_S4" superfree
bg_L7_S4_pic: .incbin "res/bg_L7_S4r.pic"
bg_L7_S4_picend:
bg_L7_S4_map: .incbin "res/bg_L7_S4r.map"
bg_L7_S4_pal: .incbin "res/bg_L7_S4r.pal"
.ends

.section ".rodata_bg_L7_S5" superfree
bg_L7_S5_pic: .incbin "res/bg_L7_S5r.pic"
bg_L7_S5_picend:
bg_L7_S5_map: .incbin "res/bg_L7_S5r.map"
bg_L7_S5_pal: .incbin "res/bg_L7_S5r.pal"
.ends

.section ".rodata_bg_L7_S6" superfree
bg_L7_S6_pic: .incbin "res/bg_L7_S6r.pic"
bg_L7_S6_picend:
bg_L7_S6_map: .incbin "res/bg_L7_S6r.map"
bg_L7_S6_pal: .incbin "res/bg_L7_S6r.pal"
.ends

.section ".rodata_bg_L7_S7" superfree
bg_L7_S7_pic: .incbin "res/bg_L7_S7r.pic"
bg_L7_S7_picend:
bg_L7_S7_map: .incbin "res/bg_L7_S7r.map"
bg_L7_S7_pal: .incbin "res/bg_L7_S7r.pal"
.ends

.section ".rodata_bg_L7_S8" superfree
bg_L7_S8_pic: .incbin "res/bg_L7_S8r.pic"
bg_L7_S8_picend:
bg_L7_S8_map: .incbin "res/bg_L7_S8r.map"
bg_L7_S8_pal: .incbin "res/bg_L7_S8r.pal"
.ends

.section ".rodata_bg_L7_S9" superfree
bg_L7_S9_pic: .incbin "res/bg_L7_S9r.pic"
bg_L7_S9_picend:
bg_L7_S9_map: .incbin "res/bg_L7_S9r.map"
bg_L7_S9_pal: .incbin "res/bg_L7_S9r.pal"
.ends

.section ".rodata_bg_L7_S10" superfree
bg_L7_S10_pic: .incbin "res/bg_L7_S10r.pic"
bg_L7_S10_picend:
bg_L7_S10_map: .incbin "res/bg_L7_S10r.map"
bg_L7_S10_pal: .incbin "res/bg_L7_S10r.pal"
.ends

.section ".rodata_bg_L7_S11" superfree
bg_L7_S11_pic: .incbin "res/bg_L7_S11r.pic"
bg_L7_S11_picend:
bg_L7_S11_map: .incbin "res/bg_L7_S11r.map"
bg_L7_S11_pal: .incbin "res/bg_L7_S11r.pal"
.ends

.section ".rodata_bg_L7_S12" superfree
bg_L7_S12_pic: .incbin "res/bg_L7_S12r.pic"
bg_L7_S12_picend:
bg_L7_S12_map: .incbin "res/bg_L7_S12r.map"
bg_L7_S12_pal: .incbin "res/bg_L7_S12r.pal"
.ends

.section ".rodata_bg_L7_S13" superfree
bg_L7_S13_pic: .incbin "res/bg_L7_S13r.pic"
bg_L7_S13_picend:
bg_L7_S13_map: .incbin "res/bg_L7_S13r.map"
bg_L7_S13_pal: .incbin "res/bg_L7_S13r.pal"
.ends

.section ".rodata_bg_L7_S14" superfree
bg_L7_S14_pic: .incbin "res/bg_L7_S14r.pic"
bg_L7_S14_picend:
bg_L7_S14_map: .incbin "res/bg_L7_S14r.map"
bg_L7_S14_pal: .incbin "res/bg_L7_S14r.pal"
.ends

.section ".rodata_bg_L7_S15" superfree
bg_L7_S15_pic: .incbin "res/bg_L7_S15r.pic"
bg_L7_S15_picend:
bg_L7_S15_map: .incbin "res/bg_L7_S15r.map"
bg_L7_S15_pal: .incbin "res/bg_L7_S15r.pal"
.ends

.section ".rodata_bg_L8_S0" superfree
bg_L8_S0_pic: .incbin "res/bg_L8_S0r.pic"
bg_L8_S0_picend:
bg_L8_S0_map: .incbin "res/bg_L8_S0r.map"
bg_L8_S0_pal: .incbin "res/bg_L8_S0r.pal"
.ends

.section ".rodata_bg_L8_S1" superfree
bg_L8_S1_pic: .incbin "res/bg_L8_S1r.pic"
bg_L8_S1_picend:
bg_L8_S1_map: .incbin "res/bg_L8_S1r.map"
bg_L8_S1_pal: .incbin "res/bg_L8_S1r.pal"
.ends

.section ".rodata_bg_L8_S2" superfree
bg_L8_S2_pic: .incbin "res/bg_L8_S2r.pic"
bg_L8_S2_picend:
bg_L8_S2_map: .incbin "res/bg_L8_S2r.map"
bg_L8_S2_pal: .incbin "res/bg_L8_S2r.pal"
.ends

.section ".rodata_bg_L8_S3" superfree
bg_L8_S3_pic: .incbin "res/bg_L8_S3r.pic"
bg_L8_S3_picend:
bg_L8_S3_map: .incbin "res/bg_L8_S3r.map"
bg_L8_S3_pal: .incbin "res/bg_L8_S3r.pal"
.ends

.section ".rodata_bg_L8_S4" superfree
bg_L8_S4_pic: .incbin "res/bg_L8_S4r.pic"
bg_L8_S4_picend:
bg_L8_S4_map: .incbin "res/bg_L8_S4r.map"
bg_L8_S4_pal: .incbin "res/bg_L8_S4r.pal"
.ends

.section ".rodata_bg_L8_S5" superfree
bg_L8_S5_pic: .incbin "res/bg_L8_S5r.pic"
bg_L8_S5_picend:
bg_L8_S5_map: .incbin "res/bg_L8_S5r.map"
bg_L8_S5_pal: .incbin "res/bg_L8_S5r.pal"
.ends

.section ".rodata_bg_L8_S6" superfree
bg_L8_S6_pic: .incbin "res/bg_L8_S6r.pic"
bg_L8_S6_picend:
bg_L8_S6_map: .incbin "res/bg_L8_S6r.map"
bg_L8_S6_pal: .incbin "res/bg_L8_S6r.pal"
.ends

.section ".rodata_bg_L8_S7" superfree
bg_L8_S7_pic: .incbin "res/bg_L8_S7r.pic"
bg_L8_S7_picend:
bg_L8_S7_map: .incbin "res/bg_L8_S7r.map"
bg_L8_S7_pal: .incbin "res/bg_L8_S7r.pal"
.ends

.section ".rodata_bg_L8_S8" superfree
bg_L8_S8_pic: .incbin "res/bg_L8_S8r.pic"
bg_L8_S8_picend:
bg_L8_S8_map: .incbin "res/bg_L8_S8r.map"
bg_L8_S8_pal: .incbin "res/bg_L8_S8r.pal"
.ends

.section ".rodata_bg_L8_S9" superfree
bg_L8_S9_pic: .incbin "res/bg_L8_S9r.pic"
bg_L8_S9_picend:
bg_L8_S9_map: .incbin "res/bg_L8_S9r.map"
bg_L8_S9_pal: .incbin "res/bg_L8_S9r.pal"
.ends

.section ".rodata_bg_L8_S10" superfree
bg_L8_S10_pic: .incbin "res/bg_L8_S10r.pic"
bg_L8_S10_picend:
bg_L8_S10_map: .incbin "res/bg_L8_S10r.map"
bg_L8_S10_pal: .incbin "res/bg_L8_S10r.pal"
.ends

.section ".rodata_bg_L8_S11" superfree
bg_L8_S11_pic: .incbin "res/bg_L8_S11r.pic"
bg_L8_S11_picend:
bg_L8_S11_map: .incbin "res/bg_L8_S11r.map"
bg_L8_S11_pal: .incbin "res/bg_L8_S11r.pal"
.ends

.section ".rodata_bg_L8_S12" superfree
bg_L8_S12_pic: .incbin "res/bg_L8_S12r.pic"
bg_L8_S12_picend:
bg_L8_S12_map: .incbin "res/bg_L8_S12r.map"
bg_L8_S12_pal: .incbin "res/bg_L8_S12r.pal"
.ends

.section ".rodata_bg_L8_S13" superfree
bg_L8_S13_pic: .incbin "res/bg_L8_S13r.pic"
bg_L8_S13_picend:
bg_L8_S13_map: .incbin "res/bg_L8_S13r.map"
bg_L8_S13_pal: .incbin "res/bg_L8_S13r.pal"
.ends

.section ".rodata_bg_L8_S14" superfree
bg_L8_S14_pic: .incbin "res/bg_L8_S14r.pic"
bg_L8_S14_picend:
bg_L8_S14_map: .incbin "res/bg_L8_S14r.map"
bg_L8_S14_pal: .incbin "res/bg_L8_S14r.pal"
.ends

.section ".rodata_bg_L8_S15" superfree
bg_L8_S15_pic: .incbin "res/bg_L8_S15r.pic"
bg_L8_S15_picend:
bg_L8_S15_map: .incbin "res/bg_L8_S15r.map"
bg_L8_S15_pal: .incbin "res/bg_L8_S15r.pal"
.ends

.section ".rodata_bg_L9_S0" superfree
bg_L9_S0_pic: .incbin "res/bg_L9_S0r.pic"
bg_L9_S0_picend:
bg_L9_S0_map: .incbin "res/bg_L9_S0r.map"
bg_L9_S0_pal: .incbin "res/bg_L9_S0r.pal"
.ends

.section ".rodata_bg_L9_S1" superfree
bg_L9_S1_pic: .incbin "res/bg_L9_S1r.pic"
bg_L9_S1_picend:
bg_L9_S1_map: .incbin "res/bg_L9_S1r.map"
bg_L9_S1_pal: .incbin "res/bg_L9_S1r.pal"
.ends

.section ".rodata_bg_L9_S2" superfree
bg_L9_S2_pic: .incbin "res/bg_L9_S2r.pic"
bg_L9_S2_picend:
bg_L9_S2_map: .incbin "res/bg_L9_S2r.map"
bg_L9_S2_pal: .incbin "res/bg_L9_S2r.pal"
.ends

.section ".rodata_bg_L9_S3" superfree
bg_L9_S3_pic: .incbin "res/bg_L9_S3r.pic"
bg_L9_S3_picend:
bg_L9_S3_map: .incbin "res/bg_L9_S3r.map"
bg_L9_S3_pal: .incbin "res/bg_L9_S3r.pal"
.ends

.section ".rodata_bg_L9_S4" superfree
bg_L9_S4_pic: .incbin "res/bg_L9_S4r.pic"
bg_L9_S4_picend:
bg_L9_S4_map: .incbin "res/bg_L9_S4r.map"
bg_L9_S4_pal: .incbin "res/bg_L9_S4r.pal"
.ends

.section ".rodata_bg_L9_S5" superfree
bg_L9_S5_pic: .incbin "res/bg_L9_S5r.pic"
bg_L9_S5_picend:
bg_L9_S5_map: .incbin "res/bg_L9_S5r.map"
bg_L9_S5_pal: .incbin "res/bg_L9_S5r.pal"
.ends

.section ".rodata_bg_L9_S6" superfree
bg_L9_S6_pic: .incbin "res/bg_L9_S6r.pic"
bg_L9_S6_picend:
bg_L9_S6_map: .incbin "res/bg_L9_S6r.map"
bg_L9_S6_pal: .incbin "res/bg_L9_S6r.pal"
.ends

.section ".rodata_bg_L9_S7" superfree
bg_L9_S7_pic: .incbin "res/bg_L9_S7r.pic"
bg_L9_S7_picend:
bg_L9_S7_map: .incbin "res/bg_L9_S7r.map"
bg_L9_S7_pal: .incbin "res/bg_L9_S7r.pal"
.ends

.section ".rodata_bg_L9_S8" superfree
bg_L9_S8_pic: .incbin "res/bg_L9_S8r.pic"
bg_L9_S8_picend:
bg_L9_S8_map: .incbin "res/bg_L9_S8r.map"
bg_L9_S8_pal: .incbin "res/bg_L9_S8r.pal"
.ends

.section ".rodata_bg_L9_S9" superfree
bg_L9_S9_pic: .incbin "res/bg_L9_S9r.pic"
bg_L9_S9_picend:
bg_L9_S9_map: .incbin "res/bg_L9_S9r.map"
bg_L9_S9_pal: .incbin "res/bg_L9_S9r.pal"
.ends

.section ".rodata_bg_L9_S10" superfree
bg_L9_S10_pic: .incbin "res/bg_L9_S10r.pic"
bg_L9_S10_picend:
bg_L9_S10_map: .incbin "res/bg_L9_S10r.map"
bg_L9_S10_pal: .incbin "res/bg_L9_S10r.pal"
.ends

.section ".rodata_bg_L9_S11" superfree
bg_L9_S11_pic: .incbin "res/bg_L9_S11r.pic"
bg_L9_S11_picend:
bg_L9_S11_map: .incbin "res/bg_L9_S11r.map"
bg_L9_S11_pal: .incbin "res/bg_L9_S11r.pal"
.ends

.section ".rodata_bg_L9_S12" superfree
bg_L9_S12_pic: .incbin "res/bg_L9_S12r.pic"
bg_L9_S12_picend:
bg_L9_S12_map: .incbin "res/bg_L9_S12r.map"
bg_L9_S12_pal: .incbin "res/bg_L9_S12r.pal"
.ends

.section ".rodata_bg_L9_S13" superfree
bg_L9_S13_pic: .incbin "res/bg_L9_S13r.pic"
bg_L9_S13_picend:
bg_L9_S13_map: .incbin "res/bg_L9_S13r.map"
bg_L9_S13_pal: .incbin "res/bg_L9_S13r.pal"
.ends

.section ".rodata_bg_L9_S14" superfree
bg_L9_S14_pic: .incbin "res/bg_L9_S14r.pic"
bg_L9_S14_picend:
bg_L9_S14_map: .incbin "res/bg_L9_S14r.map"
bg_L9_S14_pal: .incbin "res/bg_L9_S14r.pal"
.ends

.section ".rodata_bg_L9_S15" superfree
bg_L9_S15_pic: .incbin "res/bg_L9_S15r.pic"
bg_L9_S15_picend:
bg_L9_S15_map: .incbin "res/bg_L9_S15r.map"
bg_L9_S15_pal: .incbin "res/bg_L9_S15r.pal"
.ends

.section ".rodata_bg_L10_S0" superfree
bg_L10_S0_pic: .incbin "res/bg_L10_S0r.pic"
bg_L10_S0_picend:
bg_L10_S0_map: .incbin "res/bg_L10_S0r.map"
bg_L10_S0_pal: .incbin "res/bg_L10_S0r.pal"
.ends

.section ".rodata_bg_L10_S1" superfree
bg_L10_S1_pic: .incbin "res/bg_L10_S1r.pic"
bg_L10_S1_picend:
bg_L10_S1_map: .incbin "res/bg_L10_S1r.map"
bg_L10_S1_pal: .incbin "res/bg_L10_S1r.pal"
.ends

.section ".rodata_bg_L10_S2" superfree
bg_L10_S2_pic: .incbin "res/bg_L10_S2r.pic"
bg_L10_S2_picend:
bg_L10_S2_map: .incbin "res/bg_L10_S2r.map"
bg_L10_S2_pal: .incbin "res/bg_L10_S2r.pal"
.ends

.section ".rodata_bg_L10_S3" superfree
bg_L10_S3_pic: .incbin "res/bg_L10_S3r.pic"
bg_L10_S3_picend:
bg_L10_S3_map: .incbin "res/bg_L10_S3r.map"
bg_L10_S3_pal: .incbin "res/bg_L10_S3r.pal"
.ends

.section ".rodata_bg_L10_S4" superfree
bg_L10_S4_pic: .incbin "res/bg_L10_S4r.pic"
bg_L10_S4_picend:
bg_L10_S4_map: .incbin "res/bg_L10_S4r.map"
bg_L10_S4_pal: .incbin "res/bg_L10_S4r.pal"
.ends

.section ".rodata_bg_L10_S5" superfree
bg_L10_S5_pic: .incbin "res/bg_L10_S5r.pic"
bg_L10_S5_picend:
bg_L10_S5_map: .incbin "res/bg_L10_S5r.map"
bg_L10_S5_pal: .incbin "res/bg_L10_S5r.pal"
.ends

.section ".rodata_bg_L10_S6" superfree
bg_L10_S6_pic: .incbin "res/bg_L10_S6r.pic"
bg_L10_S6_picend:
bg_L10_S6_map: .incbin "res/bg_L10_S6r.map"
bg_L10_S6_pal: .incbin "res/bg_L10_S6r.pal"
.ends

.section ".rodata_bg_L10_S7" superfree
bg_L10_S7_pic: .incbin "res/bg_L10_S7r.pic"
bg_L10_S7_picend:
bg_L10_S7_map: .incbin "res/bg_L10_S7r.map"
bg_L10_S7_pal: .incbin "res/bg_L10_S7r.pal"
.ends

.section ".rodata_bg_L10_S8" superfree
bg_L10_S8_pic: .incbin "res/bg_L10_S8r.pic"
bg_L10_S8_picend:
bg_L10_S8_map: .incbin "res/bg_L10_S8r.map"
bg_L10_S8_pal: .incbin "res/bg_L10_S8r.pal"
.ends

.section ".rodata_bg_L10_S9" superfree
bg_L10_S9_pic: .incbin "res/bg_L10_S9r.pic"
bg_L10_S9_picend:
bg_L10_S9_map: .incbin "res/bg_L10_S9r.map"
bg_L10_S9_pal: .incbin "res/bg_L10_S9r.pal"
.ends

.section ".rodata_bg_L10_S10" superfree
bg_L10_S10_pic: .incbin "res/bg_L10_S10r.pic"
bg_L10_S10_picend:
bg_L10_S10_map: .incbin "res/bg_L10_S10r.map"
bg_L10_S10_pal: .incbin "res/bg_L10_S10r.pal"
.ends

.section ".rodata_bg_L10_S11" superfree
bg_L10_S11_pic: .incbin "res/bg_L10_S11r.pic"
bg_L10_S11_picend:
bg_L10_S11_map: .incbin "res/bg_L10_S11r.map"
bg_L10_S11_pal: .incbin "res/bg_L10_S11r.pal"
.ends

.section ".rodata_bg_L10_S12" superfree
bg_L10_S12_pic: .incbin "res/bg_L10_S12r.pic"
bg_L10_S12_picend:
bg_L10_S12_map: .incbin "res/bg_L10_S12r.map"
bg_L10_S12_pal: .incbin "res/bg_L10_S12r.pal"
.ends

.section ".rodata_bg_L10_S13" superfree
bg_L10_S13_pic: .incbin "res/bg_L10_S13r.pic"
bg_L10_S13_picend:
bg_L10_S13_map: .incbin "res/bg_L10_S13r.map"
bg_L10_S13_pal: .incbin "res/bg_L10_S13r.pal"
.ends

.section ".rodata_bg_L10_S14" superfree
bg_L10_S14_pic: .incbin "res/bg_L10_S14r.pic"
bg_L10_S14_picend:
bg_L10_S14_map: .incbin "res/bg_L10_S14r.map"
bg_L10_S14_pal: .incbin "res/bg_L10_S14r.pal"
.ends

.section ".rodata_bg_L10_S15" superfree
bg_L10_S15_pic: .incbin "res/bg_L10_S15r.pic"
bg_L10_S15_picend:
bg_L10_S15_map: .incbin "res/bg_L10_S15r.map"
bg_L10_S15_pal: .incbin "res/bg_L10_S15r.pal"
.ends
