/* Generated by tools/build_audio.py - SFX indices in res/sfx.it */
#ifndef AUDIO_SFX_H
#define AUDIO_SFX_H

/* 0-based effect indices for spcLoadEffect/spcEffect */
#define SFX_COLLECT    0
#define SFX_CRUSH      1
#define SFX_DEATH      2
#define SFX_FALL       3
#define SFX_ZAP        4
#define SFX_ENEMYKILL  5
#define SFX_BONUS      6
#define SFX_EXTRALIFE  7
#define SFX_NOENTRY    8
#define SFX_MENUMOVE   9
#define SFX_MENUSEL    10
#define SFX_PORTAL     11

#define SFX_COUNT 12

#endif
