/* Auto-generated by tools/convert_levels.py - do not edit. */
#ifndef LEVELS_H
#define LEVELS_H
#include "types.h"

extern const LevelConfig level_configs[MAX_LEVELS];
/* level_data[n] = sections*13*16 bytes, sections row-major (row*cols+col). */
extern const u8* const level_data[MAX_LEVELS];

#endif /* LEVELS_H */
