/* Auto-generated by tools/build_songs.py (make songs) -- DO NOT EDIT.
 * Order layout of the combined level modules: the frantic/portal theme
 * occupies orders 0.., then the calm level theme. Used by audio.c to swap
 * sections with a cheap spcPlay() instead of a blocking module reload. */
#ifndef MUSIC_LAYOUT_H
#define MUSIC_LAYOUT_H

#define MUSIC_FRANTIC_START 0
#define MUSIC_CALM_START    4

#endif /* MUSIC_LAYOUT_H */
