/* Auto-generated by tools/build_songs.py (make songs) -- DO NOT EDIT.
 * Order layout of the combined level modules: the frantic/portal theme
 * occupies orders 0.., then the calm level theme. Used by audio.c to swap
 * sections with a cheap spcPlay() instead of a blocking module reload. */
#ifndef MUSIC_LAYOUT_H
#define MUSIC_LAYOUT_H

#define MUSIC_FRANTIC_START 0
#define MUSIC_CALM_START    4

/* One-shot jingle lengths (60Hz frames): audio.c stops the track after
 * this many frames so it plays exactly once instead of looping. */
#define MUSIC_GAMEOVER_FRAMES      249
#define MUSIC_LEVELFINISHED_FRAMES 177

#endif /* MUSIC_LAYOUT_H */
