#!/usr/bin/env python3
"""Build the Deadfall SFX soundbank module (res/sfx.it) from the source MP3s.

Each gameplay sound effect -> mono, downsampled, trimmed -> one IT sample.
spcLoadEffect/spcEffect address them by 1-based index (see SFX_* in audio.h,
emitted here). ARAM is 64KB shared with the music driver, so SFX are kept low
rate + short. Long musical stingers (levelcomplete/sectioncomplete) are NOT
here; they'll be tiny music modules.
"""
import os
import subprocess
import numpy as np
from make_it import write_it

SRC = "/Users/marcovhv/projects/GIT/cubed/public/sounds"
RES = os.path.join(os.path.dirname(__file__), "..", "res")
INC = os.path.join(os.path.dirname(__file__), "..", "include")

RATE = 8000          # SFX sample rate (Hz); played at pitch=2 (=8kHz) for exact rate
MAXLEN = 0.6         # cap each SFX (seconds) to fit ARAM (64KB shared with music)

# (C name, source file[, max seconds]). Order defines the 1-based SFX index.
SFX = [
    ("COLLECT",   "c-collect"),
    ("CRUSH",     "c-crush"),
    ("DEATH",     "c-death"),
    ("FALL",      "c-fall"),
    ("ZAP",       "zap"),
    ("ENEMYKILL", "enemykill"),
    ("BONUS",     "bonus"),
    ("EXTRALIFE", "extralife"),
    ("NOENTRY",   "noentry"),
    ("MENUMOVE",  "menu-move"),
    ("MENUSEL",   "menu-select"),
    ("PORTAL",    "portal"),
    # NOTE: sectioncomplete.mp3 (2s) is intentionally NOT here -- a resident effect
    # this long broke boot (corrupts the effect load before the logo drops -> black
    # screen). A short section-clear cue must stay <=0.6s like the others, or be a
    # separate music stinger.
]


def decode(name, maxlen=MAXLEN):
    raw = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", f"{SRC}/{name}.mp3",
         "-ac", "1", "-ar", str(RATE), "-f", "s16le", "-"],
        capture_output=True, check=True).stdout
    pcm = np.frombuffer(raw, dtype="<i2").astype(np.float32)
    if len(pcm) == 0:
        return np.zeros(16, np.int16)
    # trim trailing near-silence
    thr = max(200.0, np.abs(pcm).max() * 0.02)
    nz = np.where(np.abs(pcm) > thr)[0]
    if len(nz):
        pcm = pcm[: min(len(pcm), nz[-1] + RATE // 50)]
    pcm = pcm[: int(maxlen * RATE)]
    # normalise a touch and pad to a multiple of 16 (BRR block size)
    peak = np.abs(pcm).max()
    if peak > 0:
        pcm = pcm * (28000.0 / peak)
    pad = (-len(pcm)) % 16
    if pad:
        pcm = np.concatenate([pcm, np.zeros(pad, np.float32)])
    return np.clip(pcm, -32768, 32767).astype(np.int16)


def main():
    samples = []
    total = 0
    for entry in SFX:
        cname, fname = entry[0], entry[1]
        mlen = entry[2] if len(entry) > 2 else MAXLEN
        pcm = decode(fname, mlen)
        total += len(pcm)
        samples.append({"name": cname, "pcm": pcm, "rate": RATE, "loop": None})
        print(f"  {cname:10s} {len(pcm):6d} samples ({len(pcm)/RATE:.2f}s)")
    out = os.path.join(RES, "sfx.it")
    n = write_it(out, "DEADFALL SFX", samples, channels=8)
    brr_est = total * 9 // 16
    print(f"wrote {out}: {n} bytes, {len(samples)} SFX, ~{brr_est/1024:.1f}KB BRR (ARAM)")

    # emit include/audio_sfx.h with the 1-based indices
    with open(os.path.join(INC, "audio_sfx.h"), "w") as f:
        f.write("/* Generated by tools/build_audio.py - SFX indices in res/sfx.it */\n")
        f.write("#ifndef AUDIO_SFX_H\n#define AUDIO_SFX_H\n\n")
        f.write("/* 0-based effect indices for spcLoadEffect/spcEffect */\n")
        for i, entry in enumerate(SFX):
            f.write(f"#define SFX_{entry[0]:10s} {i}\n")
        f.write(f"\n#define SFX_COUNT {len(SFX)}\n")
        f.write("\n#endif\n")
    print(f"wrote include/audio_sfx.h ({len(SFX)} indices)")


if __name__ == "__main__":
    main()
