#!/usr/bin/env python3
"""Convert every song in songs/ into a snesmod chiptune module in res/.

Two sources, both producing synth-voice .it modules the existing engine plays
(so SFX keep working):
  - songs/<name>.mid  -> mid2it (real MIDI composition; PREFERRED)
  - songs/*.zip MML   -> mml2it (AddmusicK score ripped from an .spc)

A songs/<out>.mid OVERRIDES the .zip for that output (e.g. songs/level1.mid wins
over ct1.zip). Output names map to the in-game roles wired in src/audio.c:

  ct2..ct10  -> music_level2..music_level10   (per-level themes)
  ct-portal  -> music_portal                  (all gems collected / exit open)
  ct-gameover-> music_gameover                 (game over screen)
  songs/levelN.mid -> music_levelN            (real MIDI, overrides the ct rip)

Each levelN module is COMBINED: it embeds songs/portal.mid (the frantic theme)
as a second, independently looping section ahead of the level theme, so the
exit-open swap is a cheap spcPlay position jump instead of a blocking module
reload. include/music_layout.h records the order positions audio.c jumps to.

Victory/credits reuses Golden Anthem (level10) in audio.c -- no separate module.

Run: python3 tools/build_songs.py     (called by `make songs`)
"""
import os
import sys
import glob
import zipfile
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
SONGS = os.path.join(ROOT, "songs")
INCLUDE = os.path.join(ROOT, "include")
sys.path.insert(0, HERE)
from mml2it import build_module
import mid2it

# Levels whose module embeds the frantic/portal theme as a second, independently
# looping section (so the exit-open swap is a cheap spcPlay, not a blocking
# reload). The portal MIDI is the shared frantic source for all of them.
LEVELS = [f"level{i}" for i in range(1, 11)]

# (zip basename, output module name). level1 is now sourced from songs/level1.mid
# (a real MIDI) rather than the ct1 rip, so ct1 is dropped here.
TRACKS = [
    ("ct2", "level2"), ("ct3", "level3"), ("ct4", "level4"),
    ("ct5", "level5"), ("ct6", "level6"), ("ct7", "level7"), ("ct8", "level8"),
    ("ct9", "level9"), ("ct10", "level10"),
    ("ct-portal", "portal"), ("ct-gameover", "gameover"),
]

# Optional per-track BPM overrides if the t-value heuristic sounds off when you
# audition res/<name>_preview.wav. e.g. {"level7": 150}
BPM_OVERRIDE = {}


def _wav_frames(name, fps=60):
    """Play-once length of res/<name>_preview.wav in 60Hz frames. The preview is
    the single-pass render, so its duration is exactly one playthrough -- audio.c
    counts down this many frames then stops the track, so snesmod's unconditional
    auto-loop never repeats a one-shot jingle (works even for 1-pattern modules,
    whose order position never changes)."""
    import wave
    p = os.path.join(mid2it.RES, f"{name}_preview.wav")
    if not os.path.exists(p):
        return 0
    with wave.open(p) as w:
        return int(round(w.getnframes() / float(w.getframerate()) * fps))


def write_layout_header(calm_start):
    """Emit include/music_layout.h: the order positions audio.c uses to jump
    between the calm (level) and frantic (portal) sections of a combined module,
    plus the play-once frame lengths of the one-shot jingles."""
    go = _wav_frames("gameover")
    lf = _wav_frames("levelfinished")
    path = os.path.join(INCLUDE, "music_layout.h")
    with open(path, "w") as f:
        f.write(
            "/* Auto-generated by tools/build_songs.py (make songs) -- DO NOT EDIT.\n"
            " * Order layout of the combined level modules: the frantic/portal theme\n"
            " * occupies orders 0.., then the calm level theme. Used by audio.c to swap\n"
            " * sections with a cheap spcPlay() instead of a blocking module reload. */\n"
            "#ifndef MUSIC_LAYOUT_H\n"
            "#define MUSIC_LAYOUT_H\n\n"
            "#define MUSIC_FRANTIC_START 0\n"
            f"#define MUSIC_CALM_START    {calm_start}\n\n"
            "/* One-shot jingle lengths (60Hz frames): audio.c stops the track after\n"
            " * this many frames so it plays exactly once instead of looping. */\n"
            f"#define MUSIC_GAMEOVER_FRAMES      {go}\n"
            f"#define MUSIC_LEVELFINISHED_FRAMES {lf}\n\n"
            "#endif /* MUSIC_LAYOUT_H */\n")
    print(f"wrote {path}  (MUSIC_CALM_START={calm_start}, gameover={go}f, levelfinished={lf}f)")


def main():
    total = 0
    with tempfile.TemporaryDirectory() as tmp:
        # MIDI sources first; a songs/<out>.mid replaces the matching .zip below.
        mids = {os.path.splitext(os.path.basename(m))[0]: m
                for m in glob.glob(os.path.join(SONGS, "*.mid"))}
        portal_mid = mids.get("portal")
        if not portal_mid:
            sys.exit("!! songs/portal.mid is required (the frantic theme baked into every level)")
        # Level modules embed the portal theme; everything else builds standalone.
        # (The standalone portal module is no longer needed in the soundbank, but
        #  we still build it so res/portal_preview.wav exists to audition.)
        calm_starts = []
        for out, mid in sorted(mids.items()):
            if out in LEVELS:
                _size, cs = mid2it.build_combined(portal_mid, mid, out)
                calm_starts.append(cs)
            else:
                print(f"[MIDI] {out} <- {os.path.basename(mid)}")
                mid2it.build_standalone(mid, out)
        if calm_starts:
            assert len(set(calm_starts)) == 1, \
                f"combined modules disagree on calm start order: {calm_starts}"
            write_layout_header(calm_starts[0])
        for zname, out in TRACKS:
            if out in mids:
                continue                      # a MIDI already produced this module
            zp = os.path.join(SONGS, f"{zname}.zip")
            if not os.path.exists(zp):
                print(f"!! missing {zp}"); continue
            dest = os.path.join(tmp, zname)
            with zipfile.ZipFile(zp) as z:
                z.extractall(dest)
            txts = glob.glob(os.path.join(dest, "**", "*.txt"), recursive=True)
            if not txts:
                print(f"!! no .txt MML in {zname}.zip"); continue
            total += build_module(sorted(txts)[0], out, BPM_OVERRIDE.get(out))
    print(f"\nbuilt modules ({len(mids)} from MIDI), {total/1024:.1f}KB of MML .it")


if __name__ == "__main__":
    main()
