#!/usr/bin/env python3
"""Generate per-section BG2 backgrounds: each game section gets its own 256x208
region of the level's background image, so sliding between sections reveals the
adjacent background (faithful to the original).

For each section we emit a FULL-detail tileset (~815 tiles, shown when stopped)
and a REDUCED one (~560 tiles, used while two sections must coexist in VRAM
during a slide). Files: res/bg_L<level>_S<idx>.{pic,map,pal}        (full)
                        res/bg_L<level>_S<idx>r.{pic,map,pal}       (reduced)
idx = row*cols + col  (matches world_section_index).

  python3 build_sections.py [level ...]   (default: all)
"""
import os
import sys
import make_bg

SRC = "/Users/marcovhv/projects/GIT/cubed/public/backgrounds"
RES = os.path.join(os.path.dirname(__file__), "..", "res")
CONFIGS = {1: (2, 2), 2: (2, 2), 3: (3, 3), 4: (3, 3), 5: (4, 3),
           6: (3, 4), 7: (4, 4), 8: (4, 4), 9: (4, 4), 10: (4, 4)}
REDUCED_BUDGET = 560


def build_level(n, reduced=True):
    cols, rows = CONFIGS[n]
    src = f"{SRC}/background-{n}.png"
    full_total = red_total = 0
    for r in range(rows):
        for c in range(cols):
            idx = r * cols + c
            crop = (c * 256, r * 208, c * 256 + 256, r * 208 + 208)
            nf = make_bg.convert(src, f"{RES}/bg_L{n}_S{idx}", crop=crop)
            full_total += nf
            if reduced:
                nr = make_bg.convert(src, f"{RES}/bg_L{n}_S{idx}r", crop=crop,
                                     merge_to=REDUCED_BUDGET)
                red_total += nr
    print(f"  level {n}: {cols}x{rows} = {cols*rows} sections, "
          f"full avg {full_total//(cols*rows)} tiles"
          + (f", reduced avg {red_total//(cols*rows)} tiles" if reduced else ""))


def emit_codegen():
    """Emit res/sections.asm (incbins for FULL section bgs) + include/bg_sections.h
    (externs + LevelBg table + per-level offsets). Reduced bgs are generated on
    disk but not incbin'd yet (added when the scroll engine needs them)."""
    # Reduced backgrounds (the ~560-tile pixelated versions) are used everywhere
    # so two sections fit in VRAM for the scroll-slide; ROM ~2.7MB (fits a cart).
    asm = ["; GENERATED by tools/build_sections.py - per-section reduced backgrounds\n"]
    externs, rows, offs, total = [], [], [0], 0
    for n in range(1, 11):
        cols, rows_n = CONFIGS[n]
        for idx in range(cols * rows_n):
            b = f"bg_L{n}_S{idx}"          # C symbol; data is the reduced (r) file
            r = f"{b}r"
            asm.append(f'.section ".rodata_{b}" superfree\n'
                       f'{b}_pic: .incbin "res/{r}.pic"\n{b}_picend:\n'
                       f'{b}_map: .incbin "res/{r}.map"\n{b}_pal: .incbin "res/{r}.pal"\n.ends\n')
            externs.append(f"extern char {b}_pic, {b}_picend, {b}_map, {b}_pal;")
            rows.append(f"    {{ &{b}_pic, &{b}_picend, &{b}_map, &{b}_pal }},")
            total += 1
        offs.append(total)
    with open(os.path.join(RES, "sections.asm"), "w") as f:
        f.write("\n".join(asm))
    with open(os.path.join(os.path.dirname(__file__), "..", "include", "bg_sections.h"), "w") as f:
        f.write("/* GENERATED by tools/build_sections.py */\n#ifndef BG_SECTIONS_H\n#define BG_SECTIONS_H\n\n")
        f.write("\n".join(externs))
        f.write("\n\nstatic const LevelBg bg_sections[] = {\n" + "\n".join(rows) + "\n};\n")
        f.write("static const u16 bg_section_offset[11] = {" + ",".join(str(o) for o in offs) + "};\n")
        f.write("/* section_bg(level 1..10, idx) */\n"
                "#define section_bg(lvl, idx) (&bg_sections[bg_section_offset[(lvl)-1] + (idx)])\n")
        f.write("\n#endif\n")
    print(f"codegen: {total} sections -> res/sections.asm + include/bg_sections.h")


if __name__ == "__main__":
    args = sys.argv[1:]
    if args and args[0] == "--codegen":
        emit_codegen()
    else:
        levels = [int(x) for x in args] or list(CONFIGS)
        for lv in levels:
            build_level(lv)
        emit_codegen()
