#!/usr/bin/env python3
"""Convert Deadfall JS level data + LevelConfig into C source for the SNES port.

Reads:
  ../cubed/src/levels/level1.js .. level10.js   (export const levelN = [ sections... ])
  ../cubed/src/LevelConfig.js                    (LEVELS array of config objects)

Writes:
  include/levels.h
  src/levels.c

Each level is a flat u8 array: sections * 13 rows * 16 cols, sections in row-major
order (index = row*worldCols + col). This matches the order sections are listed in
the JS files and how CubeWorld.js indexes them.
"""
import ast
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROJ = HERE.parent
SRC = (PROJ / ".." / "cubed" / "src").resolve()
LEVELS_DIR = SRC / "levels"

GRID_COLS = 16
GRID_ROWS = 13
NUM_LEVELS = 10


def strip_js_array(text: str, varname: str) -> str:
    """Return the bracketed array literal assigned to `export const <varname> =`."""
    m = re.search(r"export\s+const\s+" + re.escape(varname) + r"\s*=\s*", text)
    if not m:
        raise ValueError(f"could not find 'export const {varname}'")
    start = text.index("[", m.end())
    # Walk to the matching closing bracket.
    depth = 0
    for i in range(start, len(text)):
        c = text[i]
        if c == "[":
            depth += 1
        elif c == "]":
            depth -= 1
            if depth == 0:
                return text[start : i + 1]
    raise ValueError("unbalanced brackets")


def remove_comments(s: str) -> str:
    s = re.sub(r"//[^\n]*", "", s)
    s = re.sub(r"/\*.*?\*/", "", s, flags=re.S)
    return s


def parse_level(path: Path, varname: str):
    text = path.read_text()
    arr = strip_js_array(text, varname)
    arr = remove_comments(arr)
    arr = arr.replace(",]", "]").replace(",}", "}")  # tolerate trailing commas
    data = ast.literal_eval(arr)
    # data is a list of sections; each section is 13 rows of 16 ints.
    for si, sec in enumerate(data):
        if len(sec) != GRID_ROWS:
            raise ValueError(f"{path.name} section {si}: {len(sec)} rows (want {GRID_ROWS})")
        for ri, row in enumerate(sec):
            if len(row) != GRID_COLS:
                raise ValueError(f"{path.name} sec {si} row {ri}: {len(row)} cols")
            for v in row:
                if not (0 <= v <= 8):
                    raise ValueError(f"{path.name} sec {si} row {ri}: bad tile {v}")
    return data


def parse_config():
    text = (SRC / "LevelConfig.js").read_text()
    arr = strip_js_array(text, "LEVELS")
    arr = remove_comments(arr)
    # JS object -> python dict: quote keys, drop trailing commas.
    arr = re.sub(r"([{,]\s*)([A-Za-z_]\w*)\s*:", r'\1"\2":', arr)
    arr = re.sub(r",(\s*[}\]])", r"\1", arr)
    cfgs = ast.literal_eval(arr)
    return cfgs


def main():
    cfgs = parse_config()
    if len(cfgs) != NUM_LEVELS:
        print(f"warning: {len(cfgs)} configs (expected {NUM_LEVELS})", file=sys.stderr)

    levels = []
    for n in range(1, NUM_LEVELS + 1):
        p = LEVELS_DIR / f"level{n}.js"
        data = parse_level(p, f"level{n}")
        cfg = cfgs[n - 1]
        want = cfg["worldCols"] * cfg["worldRows"]
        # CubeWorld.js indexes row*worldCols+col and ignores extra sections.
        if len(data) < want:
            raise ValueError(
                f"level{n}: only {len(data)} sections, config needs {want} "
                f"({cfg['worldCols']}x{cfg['worldRows']})"
            )
        if len(data) > want:
            print(f"  level{n}: trimming {len(data)} -> {want} sections (extras unused)")
            data = data[:want]
        levels.append((n, data, cfg))
        gems = sum(row.count(2) for sec in data for row in sec)
        print(f"level{n}: {len(data)} sections, {gems} gems, "
              f"{cfg['worldCols']}x{cfg['worldRows']}, {cfg['enemies']} enemies")

    # ---- include/levels.h ----
    # LevelConfig is defined in types.h; here we only declare the data tables.
    h = []
    h.append("/* Auto-generated by tools/convert_levels.py - do not edit. */")
    h.append("#ifndef LEVELS_H")
    h.append("#define LEVELS_H")
    h.append('#include "types.h"')
    h.append("")
    h.append("extern const LevelConfig level_configs[MAX_LEVELS];")
    h.append("/* level_data[n] = sections*13*16 bytes, sections row-major (row*cols+col). */")
    h.append("extern const u8* const level_data[MAX_LEVELS];")
    h.append("")
    h.append("#endif /* LEVELS_H */")
    (PROJ / "include" / "levels.h").write_text("\n".join(h) + "\n")

    # ---- src/levels.c ----
    c = []
    c.append("/* Auto-generated by tools/convert_levels.py - do not edit. */")
    c.append('#include "levels.h"')
    c.append("")
    c.append("const LevelConfig level_configs[MAX_LEVELS] = {")
    for n, _data, cfg in levels:
        rs = cfg.get("robotSpawn", {"x": 0, "y": 0, "row": 0, "col": 0})
        c.append(
            "    {%d, %d, %d, %d, %d, %d, %d, %d, %d, %d}, /* L%d */"
            % (cfg["level"], cfg["worldCols"], cfg["worldRows"], cfg["enemies"],
               cfg["gemSprite"], cfg["robots"], rs["x"], rs["y"], rs["row"], rs["col"], n)
        )
    c.append("};")
    c.append("")

    for n, data, cfg in levels:
        c.append(f"/* Level {n}: {cfg['worldCols']}x{cfg['worldRows']} "
                 f"({len(data)} sections) */")
        c.append(f"static const u8 level_data_{n}[] = {{")
        for si, sec in enumerate(data):
            row = cfg["worldCols"] and (si // cfg["worldCols"])
            col = si % cfg["worldCols"]
            c.append(f"    /* section {si} (row {row}, col {col}) */")
            for r in sec:
                c.append("    " + ",".join(str(v) for v in r) + ",")
        c.append("};")
        c.append("")

    c.append("const u8* const level_data[MAX_LEVELS] = {")
    c.append("    " + ", ".join(f"level_data_{n}" for n in range(1, NUM_LEVELS + 1)))
    c.append("};")
    c.append("")
    (PROJ / "src" / "levels.c").write_text("\n".join(c) + "\n")

    print("\nWrote include/levels.h and src/levels.c")


if __name__ == "__main__":
    main()
