#!/usr/bin/env python3
"""Generate include/soundbank_banks.h from res/soundbank.asm.

The snesmod soundbank spans N 32KB ROM banks (symbols SOUNDBANK__0..__{N-1}); the
count depends on the combined module sizes and smconv's bank packing, so it
changes whenever the music set changes. audio.c must register EXACTLY those banks
with spcSetBank: reference one that doesn't exist -> link error ("Unresolved
SOUNDBANK__n"); fail to reference one that does -> the linker discards it and any
module living there is silent. Generating the list each build keeps them in sync.

Usage: gen_soundbank_banks.py <soundbank.asm> <out.h>   (run from the Makefile)
"""
import re
import sys

asm, out = sys.argv[1], sys.argv[2]
banks = sorted({int(m) for m in re.findall(r'SOUNDBANK__(\d+)', open(asm).read())})
n = (max(banks) + 1) if banks else 1

lines = [
    "/* AUTO-GENERATED by tools/gen_soundbank_banks.py from soundbank.asm.",
    " * Do not edit. Lists the %d ROM bank(s) the soundbank spans. */" % n,
    "#ifndef SOUNDBANK_BANKS_H",
    "#define SOUNDBANK_BANKS_H",
    "extern char " + ", ".join("SOUNDBANK__%d" % i for i in range(n)) + ";",
    "/* register highest bank first (per PVSnesLib musicGreaterThan32k) */",
    "#define SPC_SET_ALL_BANKS() do { \\",
]
lines += ["    spcSetBank(&SOUNDBANK__%d); \\" % i for i in range(n - 1, -1, -1)]
lines += ["} while (0)", "#endif", ""]

with open(out, "w") as f:
    f.write("\n".join(lines))
print("gen_soundbank_banks: %d bank(s) -> %s" % (n, out))
